import type { Metadata } from 'next';
import './globals.css';
import { Toaster } from 'react-hot-toast';

export const metadata: Metadata = {
  title: 'Yusuf Tijani',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`} suppressHydrationWarning={true}>
        {children}
        <Toaster
          toastOptions={{
            success: {
              iconTheme: {
                primary: '#f68338',
                secondary: 'fff',
              },
            },
          }}
        />
      </body>
    </html>
  );
}
